log:
  logPath: ./logs
  logName: insight-api

mysql:
  user: root
  password: xiaoguang
  address: 127.0.0.1:3306
  name: insight_db

wx:
  appid: wx8075ba28a91336ff
  secret: b28d61164d93f5a29529aa9e52f79087